version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - exhaustive
    - noctx
    - bodyclose
    - contextcheck
formatters:
  enable:
    - gofmt
    - goimports
linters-settings:
  goimports:
    local-prefixes: github.com/lega4e/mcp-auto
  revive:
    rules:
      - name: exported
      - name: error-return
      - name: error-strings
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
