package builder

var registeredTargets = map[string]targetSpec{
	TargetProxy:    proxyTarget,
	TargetOperator: operatorTarget,
	TargetCaddy:    caddyTarget,
	TargetKong:     kongTarget,
}

// proxyTarget generates a standalone mcp-auto proxy binary.
// The Packages list replaces the default cmd/proxy/deps bundle.
var proxyTarget = targetSpec{
	mainTemplate: `// Code generated by mcp-auto builder. DO NOT EDIT.
package main

import (
	"context"
	"errors"
	"log/slog"
	"os"
	"os/signal"
	"syscall"

	"github.com/lega4e/mcp-auto/pkg/mcpanything"
{{- range .Packages}}
	_ "{{.}}"
{{- end}}
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	cfgPath, cfg, err := mcpanything.LoadConfig()
	if err != nil {
		slog.Error("config load failed", "error", err)
		os.Exit(1)
	}

	proxy, err := mcpanything.New(ctx, cfg, mcpanything.WithConfigPath(cfgPath))
	if err != nil {
		slog.Error("startup failed", "error", err)
		os.Exit(1)
	}
	defer func() {
		if shutErr := proxy.Shutdown(context.Background()); shutErr != nil {
			slog.Error("shutdown", "error", shutErr)
		}
	}()

	if err := proxy.Start(ctx); err != nil && !errors.Is(err, context.Canceled) {
		slog.Error("server", "error", err)
		os.Exit(1)
	}
}
`,
}

// operatorTarget generates the Kubernetes operator binary.
// The Packages list is unused for the operator itself but is kept for future
// use (e.g. selective CRD field generation based on included components).
var operatorTarget = targetSpec{
	mainTemplate: `// Code generated by mcp-auto builder. DO NOT EDIT.
package main

import (
	"flag"
	"log/slog"
	"os"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
	gatewayv1 "sigs.k8s.io/gateway-api/apis/v1"

	"github.com/lega4e/mcp-auto/pkg/crd/v1alpha1"
	"github.com/lega4e/mcp-auto/pkg/operator/controller"
	operatorwebhook "github.com/lega4e/mcp-auto/pkg/operator/webhook"
)

var scheme = runtime.NewScheme()

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	utilruntime.Must(corev1.AddToScheme(scheme))
	utilruntime.Must(appsv1.AddToScheme(scheme))
	utilruntime.Must(v1alpha1.AddToScheme(scheme))
	utilruntime.Must(gatewayv1.Install(scheme))
}

func main() {
	var (
		metricsAddr          string
		healthProbeAddr      string
		enableLeaderElection bool
		namespace            string
		enableWebhooks       bool
	)

	flag.StringVar(&metricsAddr, "metrics-bind-address", ":8443", "The address the metrics endpoint binds to.")
	flag.StringVar(&healthProbeAddr, "health-probe-bind-address", ":8081", "The address the health probe endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "leader-elect", false, "Enable leader election for the operator.")
	flag.StringVar(&namespace, "namespace", "", "Restrict the operator to a single namespace. Empty means all namespaces.")
	flag.BoolVar(&enableWebhooks, "enable-webhooks", false, "Enable validating admission webhooks.")
	flag.Parse()

	mgrOpts := ctrl.Options{
		Scheme: scheme,
		Metrics: metricsserver.Options{
			BindAddress: metricsAddr,
		},
		HealthProbeBindAddress: healthProbeAddr,
		LeaderElection:         enableLeaderElection,
		LeaderElectionID:       "mcp-auto-operator.mcp-auto.ai",
	}
	if namespace != "" {
		mgrOpts.Cache.DefaultNamespaces = map[string]cache.Config{
			namespace: {},
		}
	}
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), mgrOpts)
	if err != nil {
		slog.Error("creating manager", "error", err)
		os.Exit(1)
	}

	if err := (&controller.MCPProxyReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		slog.Error("setting up MCPProxy controller", "error", err)
		os.Exit(1)
	}

	if err := (&controller.MCPUpstreamReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		slog.Error("setting up MCPUpstream controller", "error", err)
		os.Exit(1)
	}

	if enableWebhooks {
		hookServer := mgr.GetWebhookServer()
		hookServer.Register("/validate-mcp-auto-ai-v1alpha1-mcpproxy",
			admission.WithValidator[*v1alpha1.MCPProxy](mgr.GetScheme(), &operatorwebhook.MCPProxyValidator{}),
		)
		hookServer.Register("/validate-mcp-auto-ai-v1alpha1-mcpupstream",
			admission.WithValidator[*v1alpha1.MCPUpstream](mgr.GetScheme(), &operatorwebhook.MCPUpstreamValidator{}),
		)
	}

	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		slog.Error("setting up healthz check", "error", err)
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		slog.Error("setting up readyz check", "error", err)
		os.Exit(1)
	}

	slog.Info("starting mcp-auto operator",
		"metrics_addr", metricsAddr,
		"health_probe_addr", healthProbeAddr,
		"leader_elect", enableLeaderElection,
		"namespace", namespace,
		"webhooks", enableWebhooks,
	)

	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		slog.Error("running manager", "error", err)
		os.Exit(1)
	}
}
`,
}

// caddyTarget generates a Caddy binary with the mcp-auto module embedded.
// The Packages list extends the built-in components already registered by pkg/caddy
// (which includes all auth strategies, upstream builders, and scripting runtimes).
// Use Packages to add extra backends: cache stores, session stores, rate-limit stores,
// or embedding providers.
var caddyTarget = targetSpec{
	mainTemplate: `// Code generated by mcp-auto builder. DO NOT EDIT.
package main

import (
	_ "time/tzdata"

	caddycmd "github.com/caddyserver/caddy/v2/cmd"

	// Standard Caddy modules (HTTP, TLS, etc.).
	_ "github.com/caddyserver/caddy/v2/modules/standard"

	// mcp-auto Caddy middleware (registers built-in auth strategies and upstream builders).
	_ "github.com/lega4e/mcp-auto/pkg/caddy"
{{- range .Packages}}
	_ "{{.}}"
{{- end}}
)

func main() {
	caddycmd.Main()
}
`,
}

// kongTarget generates a Kong Go plugin binary wrapping mcp-auto.
// The plugin starts mcp-auto as an embedded HTTP server and rewrites the
// Kong service address to route MCP traffic through the proxy.
//
// Requires github.com/Kong/go-pdk which is downloaded at build time.
var kongTarget = targetSpec{
	extraRequire:  []string{"github.com/Kong/go-pdk v0.11.0"},
	needsDownload: true,
	mainTemplate: `// Code generated by mcp-auto builder. DO NOT EDIT.
//
// Kong Go plugin that embeds mcp-auto as an HTTP handler.
// The plugin starts a local mcp-auto server on first request and
// rewrites the Kong service address so that Kong proxies MCP traffic
// through the embedded proxy.
package main

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"sync"

	"github.com/Kong/go-pdk"
	"github.com/Kong/go-pdk/server"

	pkgconfig "github.com/lega4e/mcp-auto/pkg/config"
	"github.com/lega4e/mcp-auto/pkg/mcpanything"
{{- range .Packages}}
	_ "{{.}}"
{{- end}}
)

// Version is reported to Kong during plugin handshake.
const Version = "1.0.0"

// Priority determines the plugin execution order relative to other Kong plugins.
// Higher values run earlier in the access phase.
const Priority = 1000

// Config holds per-plugin configuration set via the Kong Admin API.
type Config struct {
	// ConfigPath is the path to the mcp-auto YAML config file.
	// When empty, the CONFIG_PATH environment variable is used, falling back
	// to /etc/mcp-auto/config.yaml.
	ConfigPath string ` + "`" + `json:"config_path"` + "`" + `
}

var (
	startOnce sync.Once
	proxyAddr string
	proxyErr  error
)

// New returns a fresh Config. Kong calls this for every request to obtain
// the plugin configuration.
func New() interface{} { return &Config{} }

// Access is called by Kong in the access phase for every proxied request.
// On the first call it starts the embedded mcp-auto server; subsequent
// calls reuse the already-running server.
func (c *Config) Access(kong *pdk.PDK) {
	startOnce.Do(func() {
		proxyAddr, proxyErr = startProxy(c.ConfigPath)
	})
	if proxyErr != nil {
		slog.Error("mcp-auto kong plugin: proxy startup failed", "error", proxyErr)
		if err := kong.Response.SetStatus(http.StatusInternalServerError); err != nil {
			slog.Error("setting status", "error", err)
		}
		return
	}
	// Rewrite the upstream service address to the embedded proxy.
	if err := kong.ServiceRequest.SetHeader("X-Forwarded-Host", proxyAddr); err != nil {
		slog.Error("mcp-auto kong plugin: setting upstream header", "error", err)
		if setErr := kong.Response.SetStatus(http.StatusBadGateway); setErr != nil {
			slog.Error("setting status", "error", setErr)
		}
	}
}

// startProxy starts mcp-auto listening on a random local port and returns
// the address (host:port).
func startProxy(cfgPath string) (string, error) {
	// Reserve a local port before starting the proxy so we know the address.
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return "", fmt.Errorf("reserving local port: %w", err)
	}
	addr := ln.Addr().String()
	if err := ln.Close(); err != nil {
		return "", fmt.Errorf("releasing port: %w", err)
	}

	var (
		path string
		cfg  *pkgconfig.ProxyConfig
	)
	if cfgPath != "" {
		path = cfgPath
		cfg, err = pkgconfig.Load(path)
	} else {
		path, cfg, err = mcpanything.LoadConfig()
	}
	if err != nil {
		return "", fmt.Errorf("loading config: %w", err)
	}

	// Override the listen address with the reserved port.
	cfg.Server.Addr = addr

	ctx := context.Background()
	proxy, err := mcpanything.New(ctx, cfg, mcpanything.WithConfigPath(path))
	if err != nil {
		return "", fmt.Errorf("creating proxy: %w", err)
	}
	proxy.StartBackground(ctx)
	go func() {
		if startErr := proxy.Start(ctx); startErr != nil && startErr != context.Canceled {
			slog.Error("mcp-auto kong plugin: proxy error", "error", startErr)
		}
	}()
	return addr, nil
}

func main() {
	server.StartServer(New, Version, Priority)
}
`,
}
