// Code generated by "go run ./cmd/crdgen". DO NOT EDIT.
// Source: pkg/config/config.go
// Regenerate with: make generate-crds

package v1alpha1

// JWTAuthConfig configures JWT Bearer token validation via OIDC/JWKS.
type JWTAuthSpec struct {
	// +optional
	Issuer string `json:"issuer,omitempty"`
	// +optional
	Audience string `json:"audience,omitempty"`
	// +optional
	// optional; uses OIDC discovery if empty
	JWKSURL string `json:"jwksUrl,omitempty"`
}

// NamingConfig controls how tool names are generated.
type NamingSpec struct {
	// +optional
	Separator string `json:"separator,omitempty"`
	// +optional
	MaxLength int `json:"maxLength,omitempty"`
	// +optional
	ConflictResolution string `json:"conflictResolution,omitempty"`
	// +optional
	DescriptionMaxLength int `json:"descriptionMaxLength,omitempty"`
	// +optional
	DescriptionTruncationSuffix string `json:"descriptionTruncationSuffix,omitempty"`
	// +optional
	DefaultSlugRules SlugRulesSpec `json:"defaultSlugRules,omitempty"`
}

// SlugRulesConfig controls which slug transformations are applied.
type SlugRulesSpec struct {
	// +optional
	ReplaceSlashes bool `json:"replaceSlashes,omitempty"`
	// +optional
	ReplaceBraces bool `json:"replaceBraces,omitempty"`
	// +optional
	// ExpandCamelCase inserts underscores at camelCase word boundaries before
	// other transformations, so operationIds like "getGreeting" become
	// "get_greeting" rather than "getgreeting".
	ExpandCamelCase bool `json:"expandCamelCase,omitempty"`
	// +optional
	Lowercase bool `json:"lowercase,omitempty"`
	// +optional
	CollapseSeparators bool `json:"collapseSeparators,omitempty"`
}

// TelemetryConfig holds observability settings.
type TelemetrySpec struct {
	// +optional
	ServiceName string `json:"serviceName,omitempty"`
	// +optional
	ServiceVersion string `json:"serviceVersion,omitempty"`
	// +optional
	// e.g. "localhost:4317"; empty = no trace exporter
	OTLPEndpoint string `json:"otlpEndpoint,omitempty"`
	// +optional
	// skip TLS for OTLP gRPC (useful in tests)
	Insecure bool `json:"insecure,omitempty"`
}

// CommandConfig defines a single command-backed MCP tool within a command upstream.
type CommandSpec struct {
	// +optional
	ToolName string `json:"toolName,omitempty"`
	// +optional
	Description string `json:"description,omitempty"`
	// +optional
	Command string `json:"command,omitempty"`
	// +optional
	InputSchema CommandInputSchema `json:"inputSchema,omitempty"`
	// +optional
	Timeout string `json:"timeout,omitempty"`
	// +optional
	Env map[string]string `json:"env,omitempty"`
	// +optional
	WorkingDir string `json:"workingDir,omitempty"`
	// +optional
	// execute via sh -c; default false (direct exec)
	Shell bool `json:"shell,omitempty"`
	// +optional
	// max bytes from stdout/stderr; 0 = 1 MiB default
	MaxOutput int64 `json:"maxOutput,omitempty"`
}

// CommandInputSchema is the JSON Schema definition for a command tool's input parameters.
type CommandInputSchema struct {
	// +optional
	Type string `json:"type,omitempty"`
	// +optional
	Properties map[string]CommandSchemaProperty `json:"properties,omitempty"`
	// +optional
	Required []string `json:"required,omitempty"`
}

// CommandSchemaProperty describes a single property in a command tool's input schema.
type CommandSchemaProperty struct {
	// +optional
	Type string `json:"type,omitempty"`
	// +optional
	Description string `json:"description,omitempty"`
}

// ValidationConfig controls runtime request and response validation against the OpenAPI schema.
type ValidationSpec struct {
	// +optional
	ValidateRequest bool `json:"validateRequest,omitempty"`
	// +optional
	ValidateResponse bool `json:"validateResponse,omitempty"`
	// +optional
	// "warn" | "fail"
	ResponseValidationFailure string `json:"responseValidationFailure,omitempty"`
	// +optional
	SuccessStatus []int `json:"successStatus,omitempty"`
	// +optional
	ErrorStatus []int `json:"errorStatus,omitempty"`
}
