// Code generated by "go run ./cmd/crdgen". DO NOT EDIT.
// Regenerate with: make generate-crds

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Upstreams",type=integer,JSONPath=".status.upstreamCount"
// +kubebuilder:printcolumn:name="Tools",type=integer,JSONPath=".status.toolCount"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

// MCPProxy is the Schema for the mcpproxies API.
type MCPProxy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +optional
	// Spec is the desired state of MCPProxy.
	Spec MCPProxySpec `json:"spec,omitempty"`
	// +optional
	// Status is the observed state of MCPProxy.
	Status MCPProxyStatus `json:"status,omitempty"`
}

// MCPProxySpec defines the desired state of MCPProxy.
type MCPProxySpec struct {
	// +optional
	// UpstreamSelector selects MCPUpstream resources by label.
	UpstreamSelector metav1.LabelSelector `json:"upstreamSelector,omitempty"`
	// +optional
	// NamespaceSelector restricts which namespaces are searched for matching MCPUpstream resources. If empty, only the same namespace as the MCPProxy is searched.
	NamespaceSelector NamespaceSelectorSpec `json:"namespaceSelector,omitempty"`
	// +optional
	// ServiceDiscovery configures annotation-based upstream discovery from Kubernetes Services.
	ServiceDiscovery *ServiceDiscoverySpec `json:"serviceDiscovery,omitempty"`
	// +kubebuilder:validation:Minimum=1
	// +optional
	// Replicas is the number of proxy pod replicas. Defaults to 1.
	Replicas *int32 `json:"replicas,omitempty"`
	// +optional
	// Image is the proxy container image. Defaults to ghcr.io/lega4e/mcp-auto:latest.
	Image string `json:"image,omitempty"`
	// +optional
	// Resources defines CPU/memory requirements for the proxy container.
	Resources corev1.ResourceRequirements `json:"resources,omitempty"`
	// +optional
	// Server configures the MCP server endpoint.
	Server ProxyServerSpec `json:"server,omitempty"`
	// +optional
	// Naming configures how MCP tool names are generated.
	Naming ProxyNamingSpec `json:"naming,omitempty"`
	// +optional
	// InboundAuth configures authentication for inbound MCP clients.
	InboundAuth *ProxyInboundAuthSpec `json:"inboundAuth,omitempty"`
	// +optional
	// Telemetry configures observability settings.
	Telemetry *ProxyTelemetrySpec `json:"telemetry,omitempty"`
}

// NamespaceSelectorSpec selects namespaces by name.
type NamespaceSelectorSpec struct {
	// +optional
	// MatchNames is a list of namespace names to search for MCPUpstream resources.
	MatchNames []string `json:"matchNames,omitempty"`
}

// ServiceDiscoverySpec configures annotation-based upstream discovery from Services.
type ServiceDiscoverySpec struct {
	// +optional
	// Enabled enables scanning for Services annotated with mcp-auto.ai/enabled=true.
	Enabled bool `json:"enabled,omitempty"`
	// +optional
	// NamespaceSelector restricts which namespaces are scanned for annotated Services. If not set, the same namespaces as NamespaceSelector are used.
	NamespaceSelector *ServiceDiscoveryNamespaceSelector `json:"namespaceSelector,omitempty"`
}

// ServiceDiscoveryNamespaceSelector restricts which namespaces are scanned for annotated Services.
type ServiceDiscoveryNamespaceSelector struct {
	// +optional
	// MatchNames is a list of specific namespace names to scan.
	MatchNames []string `json:"matchNames,omitempty"`
	// +optional
	// MatchLabels scans all namespaces whose labels match these key-value pairs.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// MCPProxyStatus defines the observed state of MCPProxy.
type MCPProxyStatus struct {
	// +optional
	// Conditions represents the latest available observations of the MCPProxy state.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// UpstreamCount is the number of MCPUpstream resources currently selected.
	UpstreamCount int `json:"upstreamCount,omitempty"`
	// AnnotatedServiceCount is the number of annotated Services currently discovered.
	AnnotatedServiceCount int `json:"annotatedServiceCount,omitempty"`
	// ToolCount is the total number of MCP tools exposed.
	ToolCount int `json:"toolCount,omitempty"`
	// ObservedGeneration is the generation of the spec last processed by the controller.
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// +kubebuilder:object:root=true

// MCPProxyList contains a list of MCPProxy.
type MCPProxyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	// Items is the list of MCPProxy resources.
	Items []MCPProxy `json:"items"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced
// +kubebuilder:printcolumn:name="Proxy",type=string,JSONPath=".status.assignedProxy"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

// MCPUpstream is the Schema for the mcpupstreams API.
type MCPUpstream struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +optional
	// Spec is the desired state of MCPUpstream.
	Spec MCPUpstreamSpec `json:"spec,omitempty"`
	// +optional
	// Status is the observed state of MCPUpstream.
	Status MCPUpstreamStatus `json:"status,omitempty"`
}

// MCPUpstreamSpec defines the desired state of MCPUpstream.
type MCPUpstreamSpec struct {
	// +kubebuilder:default=http
	// +kubebuilder:validation:Enum=http;command
	// +optional
	// Type is the upstream type: "http" (default) or "command". HTTP upstreams require baseURL/serviceRef and openapi. Command upstreams require commands and must not set baseURL/serviceRef/openapi.
	Type string `json:"type,omitempty"`
	// +optional
	// ToolPrefix is prepended to all tool names from this upstream.
	ToolPrefix string `json:"toolPrefix,omitempty"`
	// +optional
	// ServiceRef references an in-cluster Kubernetes Service. Mutually exclusive with BaseURL. Only used when Type is "http".
	ServiceRef *ServiceRefSpec `json:"serviceRef,omitempty"`
	// +optional
	// BaseURL is the base URL for the upstream HTTP API. Mutually exclusive with ServiceRef. Only used when Type is "http".
	BaseURL string `json:"baseURL,omitempty"`
	// +optional
	// OpenAPI configures the OpenAPI spec source. Required when Type is "http".
	OpenAPI MCPUpstreamOpenAPISpec `json:"openapi,omitempty"`
	// +optional
	// Overlay configures an optional OpenAPI Overlay document.
	Overlay *MCPUpstreamOverlaySpec `json:"overlay,omitempty"`
	// +optional
	// OutboundAuth configures authentication for outbound requests to the upstream.
	OutboundAuth *MCPUpstreamOutboundAuthSpec `json:"outboundAuth,omitempty"`
	// +optional
	// Transport configures HTTP transport settings for the upstream.
	Transport *MCPUpstreamTransportSpec `json:"transport,omitempty"`
	// +optional
	// Validation configures request/response validation against the OpenAPI schema.
	Validation *MCPUpstreamValidationSpec `json:"validation,omitempty"`
	// +optional
	// Commands defines command-backed MCP tools. Required when Type is "command".
	Commands []MCPUpstreamCommandSpec `json:"commands,omitempty"`
}

// ServiceRefSpec references a Kubernetes Service.
type ServiceRefSpec struct {
	// Name is the name of the Service.
	Name string `json:"name"`
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=65535
	// Port is the port the service exposes.
	Port int32 `json:"port"`
}

// MCPUpstreamOpenAPISpec configures the OpenAPI spec source.
type MCPUpstreamOpenAPISpec struct {
	// +optional
	// ConfigMapRef references a ConfigMap containing the OpenAPI spec. Mutually exclusive with URL and AutoDiscover.
	ConfigMapRef *ConfigMapKeyRef `json:"configMapRef,omitempty"`
	// +optional
	// URL is the URL from which the OpenAPI spec is fetched. Mutually exclusive with ConfigMapRef and AutoDiscover.
	URL string `json:"url,omitempty"`
	// +optional
	// AutoDiscover configures automatic OpenAPI spec discovery from the upstream. Mutually exclusive with ConfigMapRef and URL.
	AutoDiscover *AutoDiscoverSpec `json:"autoDiscover,omitempty"`
}

// ConfigMapKeyRef references a specific key within a ConfigMap.
type ConfigMapKeyRef struct {
	// Name is the name of the ConfigMap.
	Name string `json:"name"`
	// Key is the key in the ConfigMap data.
	Key string `json:"key"`
}

// AutoDiscoverSpec configures automatic OpenAPI discovery.
type AutoDiscoverSpec struct {
	// +optional
	// Path is the URL path at which the upstream serves its OpenAPI spec.
	Path string `json:"path,omitempty"`
}

// MCPUpstreamOverlaySpec configures an OpenAPI Overlay document.
type MCPUpstreamOverlaySpec struct {
	// +optional
	// ConfigMapRef references a ConfigMap containing the overlay document.
	ConfigMapRef *ConfigMapKeyRef `json:"configMapRef,omitempty"`
}

// MCPUpstreamStatus defines the observed state of MCPUpstream.
type MCPUpstreamStatus struct {
	// +optional
	// Conditions represents the latest available observations of the MCPUpstream state.
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// +optional
	// AssignedProxy is the name of the MCPProxy this upstream is currently assigned to.
	AssignedProxy string `json:"assignedProxy,omitempty"`
	// ToolCount is the number of MCP tools this upstream contributes.
	ToolCount int `json:"toolCount,omitempty"`
}

// +kubebuilder:object:root=true

// MCPUpstreamList contains a list of MCPUpstream.
type MCPUpstreamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	// Items is the list of MCPUpstream resources.
	Items []MCPUpstream `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MCPProxy{}, &MCPProxyList{})
	SchemeBuilder.Register(&MCPUpstream{}, &MCPUpstreamList{})
}
