//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDiscoverSpec) DeepCopyInto(out *AutoDiscoverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDiscoverSpec.
func (in *AutoDiscoverSpec) DeepCopy() *AutoDiscoverSpec {
	if in == nil {
		return nil
	}
	out := new(AutoDiscoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BearerSpec) DeepCopyInto(out *BearerSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BearerSpec.
func (in *BearerSpec) DeepCopy() *BearerSpec {
	if in == nil {
		return nil
	}
	out := new(BearerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTAuthSpec) DeepCopyInto(out *JWTAuthSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTAuthSpec.
func (in *JWTAuthSpec) DeepCopy() *JWTAuthSpec {
	if in == nil {
		return nil
	}
	out := new(JWTAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPProxy) DeepCopyInto(out *MCPProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPProxy.
func (in *MCPProxy) DeepCopy() *MCPProxy {
	if in == nil {
		return nil
	}
	out := new(MCPProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPProxyList) DeepCopyInto(out *MCPProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPProxyList.
func (in *MCPProxyList) DeepCopy() *MCPProxyList {
	if in == nil {
		return nil
	}
	out := new(MCPProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPProxySpec) DeepCopyInto(out *MCPProxySpec) {
	*out = *in
	in.UpstreamSelector.DeepCopyInto(&out.UpstreamSelector)
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.ServiceDiscovery != nil {
		in, out := &in.ServiceDiscovery, &out.ServiceDiscovery
		*out = new(ServiceDiscoverySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Server.DeepCopyInto(&out.Server)
	out.Naming = in.Naming
	if in.InboundAuth != nil {
		in, out := &in.InboundAuth, &out.InboundAuth
		*out = new(ProxyInboundAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(ProxyTelemetrySpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPProxySpec.
func (in *MCPProxySpec) DeepCopy() *MCPProxySpec {
	if in == nil {
		return nil
	}
	out := new(MCPProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPProxyStatus) DeepCopyInto(out *MCPProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPProxyStatus.
func (in *MCPProxyStatus) DeepCopy() *MCPProxyStatus {
	if in == nil {
		return nil
	}
	out := new(MCPProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstream) DeepCopyInto(out *MCPUpstream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstream.
func (in *MCPUpstream) DeepCopy() *MCPUpstream {
	if in == nil {
		return nil
	}
	out := new(MCPUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPUpstream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamCommandInputSchema) DeepCopyInto(out *MCPUpstreamCommandInputSchema) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]MCPUpstreamCommandSchemaProperty, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamCommandInputSchema.
func (in *MCPUpstreamCommandInputSchema) DeepCopy() *MCPUpstreamCommandInputSchema {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamCommandInputSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamCommandSchemaProperty) DeepCopyInto(out *MCPUpstreamCommandSchemaProperty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamCommandSchemaProperty.
func (in *MCPUpstreamCommandSchemaProperty) DeepCopy() *MCPUpstreamCommandSchemaProperty {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamCommandSchemaProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamCommandSpec) DeepCopyInto(out *MCPUpstreamCommandSpec) {
	*out = *in
	in.InputSchema.DeepCopyInto(&out.InputSchema)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamCommandSpec.
func (in *MCPUpstreamCommandSpec) DeepCopy() *MCPUpstreamCommandSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamCommandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamList) DeepCopyInto(out *MCPUpstreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPUpstream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamList.
func (in *MCPUpstreamList) DeepCopy() *MCPUpstreamList {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MCPUpstreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamOpenAPISpec) DeepCopyInto(out *MCPUpstreamOpenAPISpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	if in.AutoDiscover != nil {
		in, out := &in.AutoDiscover, &out.AutoDiscover
		*out = new(AutoDiscoverSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamOpenAPISpec.
func (in *MCPUpstreamOpenAPISpec) DeepCopy() *MCPUpstreamOpenAPISpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamOpenAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamOutboundAuthSpec) DeepCopyInto(out *MCPUpstreamOutboundAuthSpec) {
	*out = *in
	if in.Bearer != nil {
		in, out := &in.Bearer, &out.Bearer
		*out = new(BearerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(OAuth2Spec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamOutboundAuthSpec.
func (in *MCPUpstreamOutboundAuthSpec) DeepCopy() *MCPUpstreamOutboundAuthSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamOutboundAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamOverlaySpec) DeepCopyInto(out *MCPUpstreamOverlaySpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamOverlaySpec.
func (in *MCPUpstreamOverlaySpec) DeepCopy() *MCPUpstreamOverlaySpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamOverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamSpec) DeepCopyInto(out *MCPUpstreamSpec) {
	*out = *in
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(ServiceRefSpec)
		**out = **in
	}
	in.OpenAPI.DeepCopyInto(&out.OpenAPI)
	if in.Overlay != nil {
		in, out := &in.Overlay, &out.Overlay
		*out = new(MCPUpstreamOverlaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OutboundAuth != nil {
		in, out := &in.OutboundAuth, &out.OutboundAuth
		*out = new(MCPUpstreamOutboundAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(MCPUpstreamTransportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(MCPUpstreamValidationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]MCPUpstreamCommandSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamSpec.
func (in *MCPUpstreamSpec) DeepCopy() *MCPUpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamStatus) DeepCopyInto(out *MCPUpstreamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamStatus.
func (in *MCPUpstreamStatus) DeepCopy() *MCPUpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamTransportSpec) DeepCopyInto(out *MCPUpstreamTransportSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(UpstreamTLSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamTransportSpec.
func (in *MCPUpstreamTransportSpec) DeepCopy() *MCPUpstreamTransportSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamTransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPUpstreamValidationSpec) DeepCopyInto(out *MCPUpstreamValidationSpec) {
	*out = *in
	if in.SuccessStatus != nil {
		in, out := &in.SuccessStatus, &out.SuccessStatus
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.ErrorStatus != nil {
		in, out := &in.ErrorStatus, &out.ErrorStatus
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPUpstreamValidationSpec.
func (in *MCPUpstreamValidationSpec) DeepCopy() *MCPUpstreamValidationSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelectorSpec) DeepCopyInto(out *NamespaceSelectorSpec) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelectorSpec.
func (in *NamespaceSelectorSpec) DeepCopy() *NamespaceSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Spec) DeepCopyInto(out *OAuth2Spec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Spec.
func (in *OAuth2Spec) DeepCopy() *OAuth2Spec {
	if in == nil {
		return nil
	}
	out := new(OAuth2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInboundAuthSpec) DeepCopyInto(out *ProxyInboundAuthSpec) {
	*out = *in
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTAuthSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInboundAuthSpec.
func (in *ProxyInboundAuthSpec) DeepCopy() *ProxyInboundAuthSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyInboundAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyNamingSpec) DeepCopyInto(out *ProxyNamingSpec) {
	*out = *in
	out.DefaultSlugRules = in.DefaultSlugRules
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyNamingSpec.
func (in *ProxyNamingSpec) DeepCopy() *ProxyNamingSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyServerSpec) DeepCopyInto(out *ProxyServerSpec) {
	*out = *in
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ProxyTLSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyServerSpec.
func (in *ProxyServerSpec) DeepCopy() *ProxyServerSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySlugRulesSpec) DeepCopyInto(out *ProxySlugRulesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySlugRulesSpec.
func (in *ProxySlugRulesSpec) DeepCopy() *ProxySlugRulesSpec {
	if in == nil {
		return nil
	}
	out := new(ProxySlugRulesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTLSSpec) DeepCopyInto(out *ProxyTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTLSSpec.
func (in *ProxyTLSSpec) DeepCopy() *ProxyTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTelemetrySpec) DeepCopyInto(out *ProxyTelemetrySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTelemetrySpec.
func (in *ProxyTelemetrySpec) DeepCopy() *ProxyTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(ProxyTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDiscoveryNamespaceSelector) DeepCopyInto(out *ServiceDiscoveryNamespaceSelector) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDiscoveryNamespaceSelector.
func (in *ServiceDiscoveryNamespaceSelector) DeepCopy() *ServiceDiscoveryNamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoveryNamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDiscoverySpec) DeepCopyInto(out *ServiceDiscoverySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(ServiceDiscoveryNamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDiscoverySpec.
func (in *ServiceDiscoverySpec) DeepCopy() *ServiceDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceRefSpec) DeepCopyInto(out *ServiceRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceRefSpec.
func (in *ServiceRefSpec) DeepCopy() *ServiceRefSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamTLSSpec) DeepCopyInto(out *UpstreamTLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamTLSSpec.
func (in *UpstreamTLSSpec) DeepCopy() *UpstreamTLSSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamTLSSpec)
	in.DeepCopyInto(out)
	return out
}
