//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type that is provided as a pointer.
func (in *MCPProxy) DeepCopyInto(out *MCPProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of MCPProxy and returns it.
func (in *MCPProxy) DeepCopy() *MCPProxy {
	if in == nil {
		return nil
	}
	out := new(MCPProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MCPProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of MCPProxySpec into another object.
func (in *MCPProxySpec) DeepCopyInto(out *MCPProxySpec) {
	*out = *in
	in.UpstreamSelector.DeepCopyInto(&out.UpstreamSelector)
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Server.DeepCopyInto(&out.Server)
	out.Naming = in.Naming
	if in.InboundAuth != nil {
		in, out := &in.InboundAuth, &out.InboundAuth
		*out = new(ProxyInboundAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(ProxyTelemetrySpec)
		**out = **in
	}
	if in.ServiceDiscovery != nil {
		in, out := &in.ServiceDiscovery, &out.ServiceDiscovery
		*out = new(ServiceDiscoverySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of MCPProxySpec.
func (in *MCPProxySpec) DeepCopy() *MCPProxySpec {
	if in == nil {
		return nil
	}
	out := new(MCPProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPProxyStatus into another object.
func (in *MCPProxyStatus) DeepCopyInto(out *MCPProxyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of MCPProxyStatus.
func (in *MCPProxyStatus) DeepCopy() *MCPProxyStatus {
	if in == nil {
		return nil
	}
	out := new(MCPProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPProxyList into another object.
func (in *MCPProxyList) DeepCopyInto(out *MCPProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of MCPProxyList.
func (in *MCPProxyList) DeepCopy() *MCPProxyList {
	if in == nil {
		return nil
	}
	out := new(MCPProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MCPProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of MCPUpstream into another object.
func (in *MCPUpstream) DeepCopyInto(out *MCPUpstream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of MCPUpstream.
func (in *MCPUpstream) DeepCopy() *MCPUpstream {
	if in == nil {
		return nil
	}
	out := new(MCPUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MCPUpstream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of MCPUpstreamSpec into another object.
func (in *MCPUpstreamSpec) DeepCopyInto(out *MCPUpstreamSpec) {
	*out = *in
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(ServiceRefSpec)
		**out = **in
	}
	in.OpenAPI.DeepCopyInto(&out.OpenAPI)
	if in.Overlay != nil {
		in, out := &in.Overlay, &out.Overlay
		*out = new(MCPUpstreamOverlaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OutboundAuth != nil {
		in, out := &in.OutboundAuth, &out.OutboundAuth
		*out = new(MCPUpstreamOutboundAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(MCPUpstreamTransportSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Validation != nil {
		in, out := &in.Validation, &out.Validation
		*out = new(MCPUpstreamValidationSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of MCPUpstreamSpec.
func (in *MCPUpstreamSpec) DeepCopy() *MCPUpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamStatus into another object.
func (in *MCPUpstreamStatus) DeepCopyInto(out *MCPUpstreamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of MCPUpstreamStatus.
func (in *MCPUpstreamStatus) DeepCopy() *MCPUpstreamStatus {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamList into another object.
func (in *MCPUpstreamList) DeepCopyInto(out *MCPUpstreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MCPUpstream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of MCPUpstreamList.
func (in *MCPUpstreamList) DeepCopy() *MCPUpstreamList {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *MCPUpstreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of NamespaceSelectorSpec into another object.
func (in *NamespaceSelectorSpec) DeepCopyInto(out *NamespaceSelectorSpec) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of NamespaceSelectorSpec.
func (in *NamespaceSelectorSpec) DeepCopy() *NamespaceSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ProxyServerSpec into another object.
func (in *ProxyServerSpec) DeepCopyInto(out *ProxyServerSpec) {
	*out = *in
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ProxyTLSSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of ProxyServerSpec.
func (in *ProxyServerSpec) DeepCopy() *ProxyServerSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ProxyTLSSpec into another object.
func (in *ProxyTLSSpec) DeepCopyInto(out *ProxyTLSSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ProxyTLSSpec.
func (in *ProxyTLSSpec) DeepCopy() *ProxyTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ProxyNamingSpec into another object.
func (in *ProxyNamingSpec) DeepCopyInto(out *ProxyNamingSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ProxyNamingSpec.
func (in *ProxyNamingSpec) DeepCopy() *ProxyNamingSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyNamingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ProxyInboundAuthSpec into another object.
func (in *ProxyInboundAuthSpec) DeepCopyInto(out *ProxyInboundAuthSpec) {
	*out = *in
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(JWTAuthSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of ProxyInboundAuthSpec.
func (in *ProxyInboundAuthSpec) DeepCopy() *ProxyInboundAuthSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyInboundAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of JWTAuthSpec into another object.
func (in *JWTAuthSpec) DeepCopyInto(out *JWTAuthSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of JWTAuthSpec.
func (in *JWTAuthSpec) DeepCopy() *JWTAuthSpec {
	if in == nil {
		return nil
	}
	out := new(JWTAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ProxyTelemetrySpec into another object.
func (in *ProxyTelemetrySpec) DeepCopyInto(out *ProxyTelemetrySpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ProxyTelemetrySpec.
func (in *ProxyTelemetrySpec) DeepCopy() *ProxyTelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(ProxyTelemetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ServiceRefSpec into another object.
func (in *ServiceRefSpec) DeepCopyInto(out *ServiceRefSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ServiceRefSpec.
func (in *ServiceRefSpec) DeepCopy() *ServiceRefSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamOpenAPISpec into another object.
func (in *MCPUpstreamOpenAPISpec) DeepCopyInto(out *MCPUpstreamOpenAPISpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	if in.AutoDiscover != nil {
		in, out := &in.AutoDiscover, &out.AutoDiscover
		*out = new(AutoDiscoverSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of MCPUpstreamOpenAPISpec.
func (in *MCPUpstreamOpenAPISpec) DeepCopy() *MCPUpstreamOpenAPISpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamOpenAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ConfigMapKeyRef into another object.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy creates a deep copy of ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of AutoDiscoverSpec into another object.
func (in *AutoDiscoverSpec) DeepCopyInto(out *AutoDiscoverSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of AutoDiscoverSpec.
func (in *AutoDiscoverSpec) DeepCopy() *AutoDiscoverSpec {
	if in == nil {
		return nil
	}
	out := new(AutoDiscoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamOverlaySpec into another object.
func (in *MCPUpstreamOverlaySpec) DeepCopyInto(out *MCPUpstreamOverlaySpec) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
}

// DeepCopy creates a deep copy of MCPUpstreamOverlaySpec.
func (in *MCPUpstreamOverlaySpec) DeepCopy() *MCPUpstreamOverlaySpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamOverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of BearerSpec into another object.
func (in *BearerSpec) DeepCopyInto(out *BearerSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy creates a deep copy of BearerSpec.
func (in *BearerSpec) DeepCopy() *BearerSpec {
	if in == nil {
		return nil
	}
	out := new(BearerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamOutboundAuthSpec into another object.
func (in *MCPUpstreamOutboundAuthSpec) DeepCopyInto(out *MCPUpstreamOutboundAuthSpec) {
	*out = *in
	if in.Bearer != nil {
		in, out := &in.Bearer, &out.Bearer
		*out = new(BearerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth2 != nil {
		in, out := &in.OAuth2, &out.OAuth2
		*out = new(OAuth2Spec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of MCPUpstreamOutboundAuthSpec.
func (in *MCPUpstreamOutboundAuthSpec) DeepCopy() *MCPUpstreamOutboundAuthSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamOutboundAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of OAuth2Spec into another object.
func (in *OAuth2Spec) DeepCopyInto(out *OAuth2Spec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy creates a deep copy of OAuth2Spec.
func (in *OAuth2Spec) DeepCopy() *OAuth2Spec {
	if in == nil {
		return nil
	}
	out := new(OAuth2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of SecretRef into another object.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy creates a deep copy of SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamTransportSpec into another object.
func (in *MCPUpstreamTransportSpec) DeepCopyInto(out *MCPUpstreamTransportSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(UpstreamTLSSpec)
		**out = **in
	}
}

// DeepCopy creates a deep copy of MCPUpstreamTransportSpec.
func (in *MCPUpstreamTransportSpec) DeepCopy() *MCPUpstreamTransportSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamTransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of UpstreamTLSSpec into another object.
func (in *UpstreamTLSSpec) DeepCopyInto(out *UpstreamTLSSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of UpstreamTLSSpec.
func (in *UpstreamTLSSpec) DeepCopy() *UpstreamTLSSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of MCPUpstreamValidationSpec into another object.
func (in *MCPUpstreamValidationSpec) DeepCopyInto(out *MCPUpstreamValidationSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of MCPUpstreamValidationSpec.
func (in *MCPUpstreamValidationSpec) DeepCopy() *MCPUpstreamValidationSpec {
	if in == nil {
		return nil
	}
	out := new(MCPUpstreamValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ServiceDiscoverySpec into another object.
func (in *ServiceDiscoverySpec) DeepCopyInto(out *ServiceDiscoverySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(ServiceDiscoveryNamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of ServiceDiscoverySpec.
func (in *ServiceDiscoverySpec) DeepCopy() *ServiceDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ServiceDiscoveryNamespaceSelector into another object.
func (in *ServiceDiscoveryNamespaceSelector) DeepCopyInto(out *ServiceDiscoveryNamespaceSelector) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a deep copy of ServiceDiscoveryNamespaceSelector.
func (in *ServiceDiscoveryNamespaceSelector) DeepCopy() *ServiceDiscoveryNamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoveryNamespaceSelector)
	in.DeepCopyInto(out)
	return out
}
